version: "3"

services:
  postgres:
    image: postgres:15
    container_name: ton_nft_db
    restart: always
    ports:
      - 5432:5432
    environment:
    volumes:
      - ./postgres-data:/var/lib/postgresql/data